-- =========================================================
-- B-VAULT SUPABASE POSTGRESQL SCHEMA (Cloudflare Pages Ready)
-- Jalankan skrip ini di: Supabase Dashboard -> SQL Editor
-- =========================================================

-- 1. USERS & SESSIONS
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone_number TEXT,
  password_hash TEXT,
  role TEXT NOT NULL DEFAULT 'customer',
  google_id TEXT,
  avatar_url TEXT,
  two_factor_secret TEXT,
  is_two_factor_enabled INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token TEXT UNIQUE NOT NULL,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL
);

-- 2. CATEGORIES
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL
);

-- 3. PRODUCTS & VARIANTS
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  thumbnail_url TEXT,
  platform_name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  fulfillment_model TEXT NOT NULL DEFAULT 'HYBRID_SUPPLIER',
  duration_days INTEGER NOT NULL DEFAULT 30,
  cost_price NUMERIC NOT NULL DEFAULT 0,
  retail_price NUMERIC NOT NULL,
  input_requirement_label TEXT,
  estimated_delivery_text TEXT DEFAULT '5 - 20 Menit',
  warranty_duration_days INTEGER NOT NULL DEFAULT 30,
  activation_guide TEXT NOT NULL DEFAULT '',
  is_active INTEGER DEFAULT 1
);

-- 4. ORDERS & ITEMS
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  secure_token TEXT UNIQUE NOT NULL,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  customer_name TEXT,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  target_account_input TEXT,
  total_amount NUMERIC NOT NULL,
  payment_status TEXT NOT NULL DEFAULT 'PENDING_PAYMENT',
  payment_method TEXT NOT NULL,
  payment_reference TEXT,
  payment_channel_data TEXT,
  paid_at TIMESTAMPTZ,
  expired_at TIMESTAMPTZ NOT NULL,
  fulfilled_at TIMESTAMPTZ,
  fulfillment_duration_seconds INTEGER,
  supplier_issue INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_secure_token ON orders (secure_token);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON orders (customer_email);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  variant_id BIGINT REFERENCES product_variants(id) ON DELETE SET NULL,
  unit_price NUMERIC NOT NULL,
  cost_price NUMERIC DEFAULT 0,
  retail_price NUMERIC DEFAULT 0,
  activation_payload TEXT,
  admin_delivery_notes TEXT,
  warranty_expired_at TIMESTAMPTZ
);

-- 5. DISPATCHER LOGS & SETTINGS
CREATE TABLE IF NOT EXISTS dispatcher_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  channel TEXT NOT NULL,
  status TEXT NOT NULL,
  payload TEXT,
  error_message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS store_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- SEED DATA AWAL: Store Settings & Categories
INSERT INTO store_settings (key, value) VALUES 
  ('store_status', 'ONLINE'),
  ('operating_hours_notice', 'Pesanan di luar jam kerja (23:00 - 07:30 WIB) diproses mulai pukul 08:00 WIB'),
  ('admin_whatsapp', '085183410190'),
  ('telegram_bot_token', ''),
  ('telegram_chat_id', ''),
  ('baseline_delivered_licenses', '50')
ON CONFLICT (key) DO NOTHING;

INSERT INTO categories (name, slug) VALUES
  ('AI & Machine Learning', 'ai-machine-learning'),
  ('Desain & Video', 'desain-video'),
  ('Produktivitas & Cloud', 'produktivitas-cloud'),
  ('Developer & Utility', 'developer-utility'),
  ('Lisensi & Akun Pro', 'lisensi-pro')
ON CONFLICT (slug) DO NOTHING;
